### ISSUE TITLE
move_base costmap topic issue

### ISSUE THREAD

**Issue by gjjab** [hikashi/multi-robot-rrt-exploration-melodic#1]
The costmap topic of move base isn't have update,even have slam map
And I already check the topic name in parameter file of movebase
Then check current topic of the name (tb3_1 2 3/map ) have data update.

FYI 
![image](https://user-images.githubusercontent.com/6447620/139808356-04288223-2468-4aef-b5bc-4cbd9dfc308d.png)
![image](https://user-images.githubusercontent.com/6447620/139808839-7f116a55-d268-44e8-be62-1bbff579d2a4.png)
![image](https://user-images.githubusercontent.com/6447620/139808798-0d4670cb-c227-4931-a53c-e0c5fc1879a5.png)

**Comment by hikashi** [comment]
Hi, for movebase, I am using the TEB planner.
http://wiki.ros.org/teb_local_planner

Or you can change to DWA if you like to use your own planner.
Can you install the ROS package and try again?

Can refer to the following commit: [05fbe9b](https://github.com/hikashi/multi-robot-rrt-exploration-melodic/commit/05fbe9bbe19d2201511e8e42977445f39b39132d)

**Comment by gjjab** [comment]
OK!!
Thanks a lot!
I didn't notice that i had not install TEB PP in my PC.
I try install teb PP, then it work.
thank you for your sharing.
